-- =====================================================
-- SEED: AVALANCHE GAME LIBRARY (38 games)
-- =====================================================
INSERT INTO public.games (id, title, persona, category, difficulty, themes, description, learning_outcome, emoji, duration, xp_reward, reward_type, event_types, status) VALUES

-- ── Students ─────────────────────────────────────────────────────────
('av-explorer-quiz',  'Avalanche Explorer Quiz',   'student', 'Quiz',           'Beginner',     ARRAY['Avalanche Basics'],              'Speed-quiz on Avalanche fundamentals: history, mission, and architecture at a glance.', 'Understand what makes Avalanche unique.',   '🏔️', '4 min',  80,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('consensus-quest',   'Consensus Quest',           'student', 'Mission Quest',  'Beginner',     ARRAY['Consensus'],                     'Travel through the Snowman protocol — vote, sample, and reach finality.',                'Grasp Avalanche consensus visually.',       '❄️', '6 min', 120,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('wallet-setup',      'Wallet Setup Challenge',    'student', 'Mission Quest',  'Beginner',     ARRAY['Wallets','Testnet'],              'Create a Core wallet, fund it on Fuji, and complete your first transaction.',             'Onboard onto Avalanche in <5 min.',         '👛', '5 min', 100,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('avax-basics-rush',  'AVAX Basics Rush',          'student', 'Trivia',         'Beginner',     ARRAY['Avalanche Basics','Tokenomics'],  'Rapid-fire trivia on AVAX, gas, validators, and staking.',                              'Know the AVAX token economy.',              '⚡', '3 min',  70,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('subnet-discovery',  'Subnet Discovery Game',     'student', 'Puzzle',         'Beginner',     ARRAY['Subnets'],                       'Match real Avalanche subnets to their use cases.',                                     'Recognise the subnet landscape.',           '🧩', '5 min',  90,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('blockchain-bingo',  'Blockchain Bingo',          'student', 'Team Challenge', 'Beginner',     ARRAY['Avalanche Basics'],              'Live bingo with Avalanche terms — first to call out a row wins.',                      'Build vocabulary through play.',            '🎱', '8 min', 100,  'merch', ARRAY['IRL','Hybrid'],        'live'),
('eco-scavenger',     'Ecosystem Scavenger Hunt',  'student', 'Mission Quest',  'Beginner',     ARRAY['Ecosystem Growth'],              'Find QR clues across the venue tied to Avalanche projects.',                            'Map the live ecosystem.',                   '🗺️', '20 min',200,  'merch', ARRAY['IRL'],                 'live'),

-- ── Developers ───────────────────────────────────────────────────────
('smart-contract-sprint', 'Smart Contract Sprint',           'developer', 'Build Challenge', 'Intermediate', ARRAY['Smart Contracts','Testnet'],    'Write, compile, and deploy a Solidity contract on Fuji in record time.',                'Ship your first contract live.',            '🏁', '15 min',250,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('av-fundamentals',       'Avalanche Fundamentals Challenge','developer', 'Quiz',            'Intermediate', ARRAY['Avalanche Basics','Consensus'], 'Deep-dive quiz: X-Chain vs C-Chain vs P-Chain, Snowman++, gas dynamics.',               'Master Avalanche architecture.',            '📐', '8 min', 180,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('subnet-builder-sim',    'Subnet Builder Simulator',        'developer', 'Simulation',      'Advanced',     ARRAY['Subnets'],                      'Configure a custom subnet — validators, VM, gas token — and launch in sandbox.',        'Design production-ready subnets.',          '🧪', '20 min',320,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('bridge-the-chain',      'Bridge the Chain Puzzle',         'developer', 'Puzzle',          'Intermediate', ARRAY['Bridges'],                      'Route assets across chains using Avalanche Warp Messaging primitives.',                  'Understand cross-chain messaging.',         '🌉', '10 min',200,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('debug-the-contract',    'Debug the Contract',              'developer', 'Puzzle',          'Intermediate', ARRAY['Smart Contracts'],              'Find the bug in a Solidity contract before the timer ends.',                            'Sharpen contract review skills.',           '🐛', '7 min', 160,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('deploy-on-fuji',        'Deploy on Fuji',                  'developer', 'Mission Quest',   'Beginner',     ARRAY['Testnet','Smart Contracts'],    'Guided mission to deploy your first contract on the Fuji testnet.',                    'Learn the Fuji deploy pipeline.',           '🚧', '10 min',180,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('testnet-mission',       'Testnet Mission Mode',            'developer', 'Build Challenge', 'Advanced',     ARRAY['Testnet','Smart Contracts'],    'Complete 5 progressive mission stages on testnet.',                                    'End-to-end dApp shipping.',                 '🎯', '30 min',400,  'nft',   ARRAY['IRL','Hybrid'],        'soon'),
('vm-architect',          'VM Architect Challenge',          'developer', 'Decision Game',   'Advanced',     ARRAY['Subnets'],                      'Design choices for a custom VM — pick consensus, fee model, finality.',                 'Reason about VM trade-offs.',               '🧠', '12 min',260,  'xp',    ARRAY['Zoom','Hybrid'],       'soon'),

-- ── Builders ─────────────────────────────────────────────────────────
('eco-builder-sim',     'Ecosystem Builder Sim',         'builder', 'Simulation',      'Intermediate', ARRAY['Ecosystem Growth'],              'Run a 4-quarter simulation of growing a subnet ecosystem.',                             'Strategic ecosystem thinking.',             '🌐', '15 min',280,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('tokenomics-tycoon',   'Tokenomics Tycoon',             'builder', 'Simulation',      'Advanced',     ARRAY['Tokenomics'],                    'Design and stress-test a token economy under live market events.',                     'Ship sustainable tokenomics.',              '💱', '18 min',320,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('launch-strategy',     'Launch Strategy Challenge',     'builder', 'Decision Game',   'Intermediate', ARRAY['Launch & Adoption'],             'Sequence the right launch moves — testnet, audit, marketing, liquidity.',               'Plan a credible launch.',                   '🚦', '10 min',200,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('subnet-design-lab',   'Subnet Design Lab',             'builder', 'Build Challenge', 'Advanced',     ARRAY['Subnets'],                       'Architect a domain-specific subnet for gaming, RWA, or DeFi.',                          'Translate use case to architecture.',        '🧬', '20 min',340,  'nft',   ARRAY['IRL','Hybrid'],        'soon'),
('pmf-quest',           'Product-Market Fit Quest',      'builder', 'Mission Quest',   'Intermediate', ARRAY['Launch & Adoption'],             'Run discovery sprints with simulated user segments.',                                  'Diagnose PMF signals.',                     '🎯', '12 min',220,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('scale-the-stack',     'Scale the Stack Simulation',    'builder', 'Simulation',      'Advanced',     ARRAY['Ecosystem Growth'],              'Solve scaling bottlenecks across infra, app, and community layers.',                    'Think in systems.',                         '📈', '18 min',300,  'xp',    ARRAY['Zoom','Hybrid'],       'soon'),
('community-growth',    'Community Growth Builder',      'builder', 'Decision Game',   'Beginner',     ARRAY['Community'],                     'Choose tactics to grow an authentic Avalanche community.',                              'Avoid mercenary growth.',                   '👥', '8 min', 160,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('build-for-adoption',  'Build for Adoption',            'builder', 'Case Study',      'Intermediate', ARRAY['Launch & Adoption','Community'], 'Study real Avalanche launches and replay key decisions.',                               'Pattern-match real adoption stories.',      '📚', '15 min',240,  'nft',   ARRAY['Zoom','Hybrid'],       'soon'),

-- ── Founders ─────────────────────────────────────────────────────────
('founder-fit',        'Founder Fit Challenge',        'founder', 'Quiz',           'Beginner',     ARRAY['Launch & Adoption'],              'Assess your founder–market–chain fit on Avalanche.',                                    'Know where you stand.',                     '🧭', '6 min', 140,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('gtm-arena',          'Go-To-Market Arena',           'founder', 'Decision Game',   'Intermediate', ARRAY['Launch & Adoption'],              'Pick your wedge, channels, and partners under time pressure.',                          'Build a defensible GTM.',                   '⚔️', '12 min',240,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('pitch-deck-boss',    'Pitch Deck Boss Fight',         'founder', 'Mission Quest',   'Intermediate', ARRAY['Launch & Adoption'],              'Refine 8 deck slides under live investor critique.',                                   'A deck that closes meetings.',              '🎤', '15 min',280,  'merch', ARRAY['IRL','Hybrid'],        'live'),
('community-flywheel', 'Community Flywheel Quest',      'founder', 'Simulation',      'Intermediate', ARRAY['Community'],                      'Design loops that compound community value.',                                          'Engineer retention loops.',                 '🔁', '10 min',200,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('fundraising-sim',    'Fundraising Simulation',        'founder', 'Simulation',      'Advanced',     ARRAY['Tokenomics','Launch & Adoption'], 'Run a fundraise — terms, dilution, runway, follow-ons.',                               'Negotiate from strength.',                  '💼', '20 min',360,  'nft',   ARRAY['Zoom','Hybrid'],       'soon'),
('eco-partnership',    'Ecosystem Partnership Game',    'founder', 'Team Challenge',  'Intermediate', ARRAY['Ecosystem Growth'],               'Negotiate a partnership across two Avalanche subnets.',                                'Structure value-aligned deals.',            '🤝', '12 min',240,  'xp',    ARRAY['IRL','Hybrid'],        'live'),
('startup-decision',   'Startup Decision Lab',          'founder', 'Decision Game',   'Beginner',     ARRAY['Launch & Adoption'],              'Navigate a year of founder decisions with real consequences.',                          'Reason under uncertainty.',                 '🧪', '10 min',200,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('av-founder-path',    'Avalanche Founder Path',        'founder', 'Mission Quest',   'Intermediate', ARRAY['Ecosystem Growth','Launch & Adoption'],'Multi-stage journey from idea → grant → launch on Avalanche.',                     'See the full founder pathway.',             '🛤️', '25 min',400,  'nft',   ARRAY['Hybrid'],              'soon'),

-- ── Businesses ───────────────────────────────────────────────────────
('enterprise-integration', 'Enterprise Integration Challenge', 'business', 'Build Challenge', 'Advanced',     ARRAY['Business Use Cases'],                       'Connect a legacy system to an Avalanche subnet with audit-ready flows.',                'Integrate with confidence.',                '🏗️', '20 min',320,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('web3-business-sim',      'Web3 Business Simulation',         'business', 'Simulation',      'Intermediate', ARRAY['Business Use Cases'],                       'Operate a Web3 business across 4 quarters with shifting market events.',                'Run a sustainable Web3 business.',         '🏢', '18 min',300,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('loyalty-system',         'Loyalty System Builder',           'business', 'Build Challenge', 'Intermediate', ARRAY['Business Use Cases','NFTs'],                'Design an on-chain loyalty program with tiered NFT rewards.',                           'Translate loyalty to chain.',              '🎁', '15 min',260,  'nft',   ARRAY['IRL','Zoom','Hybrid'], 'live'),
('treasury-rewards',       'Treasury & Rewards Strategy',      'business', 'Decision Game',   'Advanced',     ARRAY['Tokenomics','Business Use Cases'],           'Allocate treasury to liquidity, ops, and rewards under risk constraints.',              'Allocate with discipline.',                '🏦', '12 min',240,  'xp',    ARRAY['Zoom','Hybrid'],       'live'),
('customer-activation',    'Customer Activation Game',         'business', 'Mission Quest',   'Intermediate', ARRAY['Community','Business Use Cases'],            'Design a customer onboarding flow that turns visitors into wallets.',                   'Ship Web3 onboarding that converts.',      '🎯', '12 min',240,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('onchain-ops-lab',        'Onchain Operations Lab',           'business', 'Simulation',      'Advanced',     ARRAY['Business Use Cases'],                       'Run finance, payroll, and reporting on-chain with simulated audits.',                   'Operate transparently on-chain.',          '⚙️', '20 min',320,  'nft',   ARRAY['Zoom','Hybrid'],       'soon'),
('business-explorer',      'Business Model Explorer',          'business', 'Decision Game',   'Beginner',     ARRAY['Business Use Cases'],                       'Match real Avalanche use cases to revenue models.',                                    'Spot fitting use cases.',                  '🔭', '8 min', 160,  'xp',    ARRAY['IRL','Zoom','Hybrid'], 'live'),
('av-use-case-sprint',     'Avalanche Use Case Sprint',        'business', 'Team Challenge',  'Intermediate', ARRAY['Business Use Cases','Launch & Adoption'],   'Team sprint to design a working Avalanche pilot for your industry.',                   'Walk away with a real plan.',              '🏃', '25 min',360,  'merch', ARRAY['IRL','Hybrid'],        'live')

ON CONFLICT (id) DO NOTHING;
